# Generated by Django 4.1.5 on 2023-01-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('location', models.CharField(choices=[('mainland', 'Mainland'), ('island', 'Island')], default='Mainland', max_length=50)),
            ],
        ),
    ]
